"""Materialise the tree that becomes the release repository.

The development repository carries everything: effect sources, the test suite,
the studio's PyInstaller recipe, the documentation. The release repository
carries only what ``uv build --all-packages`` needs, so that what is published
can be read in one sitting and diffed between versions without the noise.

The list below *is* the boundary. A file that is not named here does not reach
the release repository, and adding one is a deliberate line rather than a
side effect of where somebody put a file.

Two things are generated rather than copied:

* the workspace root, because the development one carries dev dependencies,
  pytest configuration and a build group that mean nothing there;
* the README, because a repository nobody may push to should say so at the top.

And one thing must already exist: the built ``.lefxset`` archives. They are
output in the development repository and gitignored there, and they are
*sources* in the release repository, because that is the tree the wheels are
built from. Running this without building the catalogues first is refused
rather than quietly shipping empty catalogue wheels.

    uv run python scripts/sync_release_tree.py --target ../release_preview
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGES_ROOT = REPO_ROOT / "packages"
TEMPLATE_ROOT = REPO_ROOT / ".github/release-repo"

RELEASE_REPO = "marcosudau-vps/led-ctrl-v3"
DEV_REPO = "marcosudau-vps/led_controller_respeaker-v3"

# Copied verbatim, path for path.
FILES = (
    "LICENSE",
    "config.example.yaml",
    "scripts/check_release.py",
)

# Copied whole, minus the exclusions below.
TREES = ("packages",)

EXCLUDE_DIRS = {"__pycache__", ".pytest_cache", ".ruff_cache", "build", "dist"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo"}
EXCLUDE_NAMES = {".DS_Store"}

# From .github/release-repo/ in this repository to .github/ in that one. They
# live here so they are reviewed with the code they release, and they are not
# under .github/workflows/ here so they never run here.
WORKFLOWS = {"release.yml": ".github/workflows/release.yml"}
TEMPLATES = {"README.md": "README.md", "gitignore": ".gitignore"}

ROOT_PYPROJECT = '''\
# Workspace root of the LEFX V3 release repository.
#
# Generated by scripts/sync_release_tree.py in
# {dev_repo}
# Do not edit here; edit it there.
#
# It exists only so that "uv build --all-packages" has a workspace to walk.
# There is nothing to develop in this tree: no test suite, no effect sources,
# no tooling. What is here is what gets published, and nothing else.
[project]
name = "led-ctrl-v3-release"
version = "{version}"
description = "Release tree for the LEFX V3 distributions"
requires-python = ">=3.12,<3.13"
dependencies = []

[tool.uv]
package = false

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
{sources}
'''


class SyncFailed(RuntimeError):
    pass


def workspace_version() -> str:
    text = (REPO_ROOT / "pyproject.toml").read_bytes().decode("utf-8")
    return tomllib.loads(text)["project"]["version"]


def distributions() -> list[str]:
    return sorted(
        path.parent.name for path in PACKAGES_ROOT.glob("*/pyproject.toml")
    )


def catalogue_archives() -> list[Path]:
    """Every ``.lefxset`` a catalogue distribution is supposed to be carrying.

    Found by module directory rather than by distribution name, so that a
    catalogue added or a distribution renamed is picked up without editing a
    second list that could disagree with the first.
    """
    expected = []
    for module_dir in sorted(PACKAGES_ROOT.glob("*/src/lefx/sets/*")):
        if not module_dir.is_dir() or module_dir.name == "__pycache__":
            continue
        set_name = module_dir.name.replace("_", "-")
        expected.append(module_dir / f"{set_name}.lefxset")
    return expected


def require_the_catalogues_are_built() -> None:
    missing = [path for path in catalogue_archives() if not path.is_file()]
    if missing:
        raise SyncFailed(
            "the effect catalogues have not been built, so these would be shipped empty:\n  "
            + "\n  ".join(path.relative_to(REPO_ROOT).as_posix() for path in missing)
            + "\n\nRun:  uv run python scripts/build_effects.py"
        )


def keep(path: Path) -> bool:
    if any(part in EXCLUDE_DIRS for part in path.parts):
        return False
    return path.suffix not in EXCLUDE_SUFFIXES and path.name not in EXCLUDE_NAMES


def copy_into(target: Path) -> list[Path]:
    written: list[Path] = []

    def place(source: Path, relative: str) -> None:
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        written.append(destination)

    for relative in FILES:
        source = REPO_ROOT / relative
        if not source.is_file():
            raise SyncFailed(f"{relative} is on the list but is not in this repository")
        place(source, relative)

    for tree in TREES:
        root = REPO_ROOT / tree
        for source in sorted(root.rglob("*")):
            if not source.is_file():
                continue
            relative = source.relative_to(REPO_ROOT)
            if keep(relative):
                place(source, relative.as_posix())

    for name, relative in {**WORKFLOWS, **TEMPLATES}.items():
        source = TEMPLATE_ROOT / name
        if not source.is_file():
            raise SyncFailed(f"{source.relative_to(REPO_ROOT).as_posix()} is missing")
        place(source, relative)

    version = workspace_version()
    sources = "\n".join(f'{name} = {{ workspace = true }}' for name in distributions())
    root = target / "pyproject.toml"
    root.write_text(
        ROOT_PYPROJECT.format(version=version, sources=sources, dev_repo=DEV_REPO),
        encoding="utf-8",
    )
    written.append(root)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--target", required=True, help="Directory to materialise the tree into")
    parser.add_argument(
        "--clean", action="store_true",
        help="Empty the target first, keeping only its .git directory",
    )
    args = parser.parse_args(argv)

    target = Path(args.target).expanduser().resolve()
    try:
        require_the_catalogues_are_built()

        if args.clean and target.is_dir():
            for item in target.iterdir():
                if item.name == ".git":
                    continue
                shutil.rmtree(item) if item.is_dir() else item.unlink()
        target.mkdir(parents=True, exist_ok=True)

        written = copy_into(target)
    except SyncFailed as exc:
        print(f"\nFAILED: {exc}", file=sys.stderr)
        return 1

    print(f"{len(written)} files written to {target}")
    for path in written:
        print(f"  {path.relative_to(target).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
